version: '3.8'
services:
    bot:
        build: 
            context: .
            dockerfile: bot.Dockerfile
        restart: always
        volumes:
            - "./config.json:/app/config.json"
        ports:
          - 8777:8000
        depends_on:
            - redis
    redis:
        image: redis:latest
        restart: always
    web:
        build: 
            context: .
            dockerfile: web.Dockerfile
        restart: always
        volumes:
            - "./config.json:/app/config.json"
        ports:
          - 8778:8080