version: '3.8'
services:
    bot:
        build: .
        restart: always
        volumes:
            - "./config.json:/app/config.json"
        ports:
          - 8777:8000
        depends_on:
            - redis
    redis:
        image: redis:latest
        restart: always